
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: admin
    password: admin
  data:
    redis:
      host: localhost
      port: 6379

minio:
  bucket: files
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin

